ALTER TRIGGER [GitTrigger]
	ON DATABASE
		FOR 
			CREATE_PROCEDURE, ALTER_PROCEDURE, DROP_PROCEDURE,
			CREATE_FUNCTION, ALTER_FUNCTION, DROP_FUNCTION,
			CREATE_TRIGGER, ALTER_TRIGGER, DROP_TRIGGER,
			CREATE_TABLE, ALTER_TABLE, DROP_TABLE,
			CREATE_VIEW, ALTER_VIEW, DROP_VIEW,
			CREATE_INDEX, ALTER_INDEX, DROP_INDEX,
			CREATE_SCHEMA, ALTER_SCHEMA, DROP_SCHEMA,
			CREATE_USER, ALTER_USER, DROP_USER,
			CREATE_ROLE, ALTER_ROLE, DROP_ROLE,
			CREATE_ROUTE, ALTER_ROUTE, DROP_ROUTE,
			CREATE_QUEUE, ALTER_QUEUE, DROP_QUEUE,
			RENAME
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @eventData XML = EVENTDATA();
	-- SELECT @eventData <<DEBUG EVENT DATA
	-- EXEC [Git].[dbo].[main] @eventDataReceived = @eventData
END
GO

ENABLE TRIGGER [GitTrigger] ON DATABASE
GO