ALTER TRIGGER [GitTrigger]
	ON DATABASE
		FOR 
			CREATE_PROCEDURE, ALTER_PROCEDURE, DROP_PROCEDURE,
			CREATE_FUNCTION, ALTER_FUNCTION, DROP_FUNCTION,
			CREATE_TRIGGER, ALTER_TRIGGER, DROP_TRIGGER,
			CREATE_TABLE, ALTER_TABLE, DROP_TABLE,
			CREATE_VIEW, ALTER_VIEW, DROP_VIEW,
			CREATE_INDEX, ALTER_INDEX, DROP_INDEX,
			CREATE_SCHEMA, ALTER_SCHEMA, DROP_SCHEMA,
			CREATE_USER, ALTER_USER, DROP_USER,
			CREATE_ROLE, ALTER_ROLE, DROP_ROLE,
			CREATE_ROUTE, ALTER_ROUTE, DROP_ROUTE,
			CREATE_QUEUE, ALTER_QUEUE, DROP_QUEUE,
			RENAME
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @eventData XML = EVENTDATA();
	SELECT @eventData 
	-- EXEC [Git].[dbo].[main] @eventDataReceived = @eventData
	
	DECLARE @stringXML VARCHAR(MAX) = CAST(@eventData AS VARCHAR(MAX));
	DECLARE @eCommandText VARCHAR(MAX) = @eventData.value('(/EVENT_INSTANCE/TSQLCommand)[1]',   'NVARCHAR(MAX)');
	EXEC [Git].[dbo].[saveFiles] @content = @stringXML, @fileName = 'sql.xml', @path = 'C:\Users\casa\Documents\REPO\'
	EXEC [Git].[dbo].[saveFiles] @content = @eCommandText, @fileName = 'command.sql', @path = 'C:\Users\casa\Documents\REPO\'

END
GO

ENABLE TRIGGER [GitTrigger] ON DATABASE
GO
